version: "3.8"

services:
  api:
    restart: always
    build: .
    ports:
      - "8088:8080"
    cpus: 0.25
    mem_limit: "512M"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080"

  redis:
    image: redis:6.2.6
    ports:
      - "6382:6379"
    env_file:
      - .env
    command: redis-server

  rabbitmq:
    image: rabbitmq:alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"

  celery_worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/api
    env_file:
      - .env
    cpus: 0.25
    mem_limit: "512M"
    command: celery -A config.celery worker --pool=eventlet --concurrency=500 --loglevel=INFO
    depends_on:
      - redis

  celery_beat:
    restart: always
    volumes:
      - ./:/api
    build:
      context: .
    env_file:
      - .env
    cpus: 0.25
    mem_limit: "512M"
    command: celery -A config.celery beat -S redbeat.RedBeatScheduler --loglevel=DEBUG
    depends_on:
      - redis

  locust_worker:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "locust"
    depends_on:
      - api
      - celery_worker

  flower:
    build: .
    ports:
      - "8090:8000"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "celery -A config.celery flower  --address=0.0.0.0 --port=8000"
    depends_on:
      - celery_worker
