version: "3.8"

services:
  celery_worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/api
    env_file:
      - .env
    cpus: 0.25
    mem_limit: "512M"
    command: celery -A config.worker worker --pool=eventlet --concurrency=500 --loglevel=INFO
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
    ports:
      - "6382:6379"
    env_file:
      - .env
    command: redis-server

  api:
    restart: always
    build: .
    ports:
      - "8088:8080"
    cpus: 0.25
    mem_limit: "512M"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080"
    depends_on:
      - celery_worker

  locust_worker:
    build: .
    ports:
      - "8089:8089"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "locust"
    depends_on:
      - api
      - celery_worker

  flower:
    build: .
    ports:
      - "8090:8000"
    volumes:
      - ./:/api
    environment:
      DEBUG: "true"
    env_file:
      - .env
    command: sh -c "celery -A config.worker flower  --address=0.0.0.0 --port=8000"
    depends_on:
      - celery_worker

  celery_monitoring:
    image: danihodovic/celery-exporter
    ports:
      - "8091:9808"
    command:
      - "--broker-url=redis://redis:6379/2"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "8092:9090"

  grafana:
    image: grafana/grafana:latest
    user: "$UID:$GID"
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SMTP_ENABLED=false
    ports:
      - "8093:3000"
